### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/Bridge#18]

**Comment by Apercu** [comment]
👍  (The reaction button doesn't work apparently, that's strange..)

**Comment by meriadec** [comment]
are you lying?

**Comment by Apercu** [comment]
Absolutely not 😂

**Comment by Apercu** [comment]
👍

**Comment by Apercu** [comment]
:neutral_face:

**Comment by Apercu** [comment]
![bridge](https://cloud.githubusercontent.com/assets/6033345/25289014/c319c5ea-267c-11e7-9a55-153fae94b101.png)

@meriadec What do you think?

**Comment by jonsadka** [comment]
I love this logo

**Comment by meriadec** [comment]
Awesome ! You have a Dribbble, or something?

**Comment by Apercu** [comment]
Unfortunately they were so jealous of my skills I was banned a while ago, but if you have a new invite I'm willing to go back

**Comment by Apercu** [comment]
Any okr on this?

**Comment by meriadec** [comment]
Yep. I'm totally on it! 👍

**Comment by meriadec** [comment]
Here is a first try. Basically a "bridge" over diagonal lines, with a Meslo typo.

![logo-bridge](https://cloud.githubusercontent.com/assets/315259/26698620/f5a9ef34-4716-11e7-8495-1b307f134172.png)

Opinions?

**Comment by Apercu** [comment]
Wwttffff it's so cool!!!!

Did you try without the border around the text? And maybe in comic sans?

**Comment by meriadec** [comment]
![path4371](https://cloud.githubusercontent.com/assets/315259/26699955/f4f71c42-471b-11e7-895e-22a5e5f8efb3.png)

**Comment by Apercu** [comment]
That's very nice, although after a bit of reflection maybe the first design would be better, the second one specifically.

One last try, removing only the vertical border for the first one, and try without the square for the second one, with maybe the font in white instead, if that's possible

**Comment by meriadec** [comment]
Here are the updated versions, with a subtle alternative for the second one.

![three-logos](https://cloud.githubusercontent.com/assets/315259/26801142/377faee4-4a3c-11e7-8195-ca158d33cd1a.png)

![third](https://cloud.githubusercontent.com/assets/315259/26801137/363f304a-4a3c-11e7-9a55-b13d779030e4.png)
![second](https://cloud.githubusercontent.com/assets/315259/26801138/365e397c-4a3c-11e7-98f2-c1e25998ca01.png)
![first](https://cloud.githubusercontent.com/assets/315259/26801141/37795850-4a3c-11e7-8a91-234b7b2deefb.png)

**Comment by meriadec** [comment]
My preference goes to the light one, without vertical borders.
