### ISSUE TITLE
Edit mode is toggled when typing in widget config

### ISSUE THREAD

**Issue by meriadec** [Sigsev/Bridge#20]
We need to find a way to disable the 'edit mode' toggling (actually by the `E` key) when we are typing in a widget configuration.

**Comment by Apercu** [comment]
Don't you think a binding involving two keys like <kbd>CTRL</kbd> + <kbd>E</kbd> would solve the issue?

**Comment by meriadec** [comment]
Yes, could be a quick fix, but I don't really like composed keyboard bindings for a webpage, a don't want to infer with some system defined shortcut.

Maybe we can disable the edit mode keyboard binding if we are editing a widget config?

**Comment by Apercu** [comment]
Yeah we could do that
