### ISSUE TITLE
bug: cant use

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/Bridge#26]
i wanted to set a timers for my eggs 🍳  but i cant haveit by new widget
fix plz

**Comment by meriadec** [comment]
have also this error
np`m ERR! Darwin 15.5.0
npm ERR! argv "C:\Documents and settings\Utilisateur Windows\.AppData\Frameworks\Library32\%MICROSOFT%\npm" " "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path C:\Documents and settings\Utilisateur Windows\Mon Premier projet-web\package.JSON
npm ERR! code ENOENT
np`m ERR! errno -2
npm ERR! syscall open

`npm ERR! enoent ENOENT: no such file or directory, open '/C:\Documents and settings\Utilisateur Windows\Mon Premier projet-web\package.JSON
npm ERR! enoent ENOENT: no such file or directory, open '/C:\Documents and settings\Utilisateur Windows\Mon Premier projet-web\package.JSON
n`pm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /nfs/2013/m/mpillet/npm-debug.log

**Comment by Apercu** [comment]
You should update the extension to 2.6, and then uninstall your OS. It's kinda strange to have both references to `/C:\Documents and settings\Utilisateur Windows\Mon Premier projet-web\` and `/nfs/2013/m/mpillet/npm-debug.log`, I advice you to use Mint, Ubuntu or Red Hat.

**Comment by meriadec** [comment]
got a black screen(currently on phone) any idea?
thx help

![u](https://cloud.githubusercontent.com/assets/315259/15791603/95c49c7e-29d8-11e6-91e7-29f15e7ab0e5.png)

**Comment by Apercu** [comment]
Oh, let me reopen this then.

I think you need to heat your phone a bit for the colors to appear again, do you still have the stove you used to cook your eggs? A quick fix would be to put your phone in it at high temperature for about 9 or 10 minutes, although best results have been noted using microwaves.

Let me see how it goes, preferably with a picture to show me you did correctly

**Comment by meriadec** [comment]
ok thx dude, well i did it and it actually worked! the timer started in my phone for unexpected reason.
nice quickaround! how do i close

![egg](https://cloud.githubusercontent.com/assets/315259/15791815/d94f4718-29d9-11e6-88b3-ca5d99a0bb59.jpg)

**Comment by Apercu** [comment]
Cool, it's the button saying **Close**, your know.

**Comment by meriadec** [comment]
eave a comment
