### ISSUE TITLE
Weather widget broken

### ISSUE THREAD

**Issue by Apercu** [SIGSEV/Bridge#28]

**Comment by meriadec** [comment]
shit.. forced to look at the window now :D

**Comment by Apercu** [comment]
Oh you have a window? What a lucky bastard

![](http://sts.wustl.edu/wp-content/uploads/2014/11/Rosedale-West-Lab.jpg)

**Comment by meriadec** [comment]
Yeah. I'm a privileged white male who owns a window and I should die for that! :D
