### ISSUE TITLE
Darksky is shit and slow

### ISSUE THREAD

**Issue by balthazar** [SIGSEV/Bridge#30]

**Comment by meriadec** [comment]
yeah. i found something awesome to check the weather: it's actually looking the sky through the window. for example, if I see some rain, I know that it's raining. opinion?

**Comment by meriadec** [comment]
ping @torvalds

**Comment by torvaIds** [comment]
What's wrong with you, guys?

**Comment by meriadec** [comment]
Sorry didn't want to distract you from the Kernel.

**Comment by torvaIds** [comment]
This is toxic and should be stopped.

**Comment by meriadec** [comment]
Chill out, dude, was just a prank.

**Comment by Apercu** [comment]
@torvaIds The ping was not intended to be actually sent and was deleted quickly but unfortunately the mail got sent to you, sorry for the disturbance, it won't happen again.

**Comment by Apercu** [comment]
@torvaIds The ping was not intended to be actually sent and was deleted quickly, unfortunately the mail got sent to you, sorry for the disturbance, it won't happen again.

**Comment by dope** [comment]
dYING

**Comment by balthazar** [comment]
Was actually due to the geolocation resolving delay. Caching it since https://github.com/SIGSEV/Bridge/commit/8fb41600311a0f5fc3aa9972c639f9f832ec04ff brings down the loading time drastically.
