### ISSUE TITLE
502 error

### ISSUE THREAD

**Issue by dope** [SIGSEV/Bridge#31]
Getting loading issue as the API seems to be down http://bridge.sigsev.io

**Comment by balthazar** [comment]
Little server issue, our technicians are working on site to fix the outage. We apologize for the inconvenience while we bring back the Zavatta services fully online. A full postmortem will be released in the next few hours.

**Comment by balthazar** [comment]
We are relieved to announce the end of the incident involving our Pacific cluster, bringing our availability down to `99.999%`. Here is the postmortem:

At `12:17 PM PST`, a cosmic ray struck our datacenter in Canada, causing a wild range of binary overflows triggering an on-chain bus error leading to a final BSOD. Our failover system should have been activated after a 42ms timeout, but a cat unfortunately cut out second power supply the same morning. After a few `var_dump`, our architect managed to do a `PATCH` request to the datacenter, while a technician manually rebooted the services.

Here is an illustration of how it happened from our graphist

![kyle](https://user-images.githubusercontent.com/6033345/33519598-98fa8d24-d75e-11e7-8975-3d8a4eb4b541.gif)

He hope this incident won't affect your confidence in the SIGSEV product and services that are delivered in exchange of ⭐️  tokens on the GitHub platform.

Also please take some time to complete our survey and give a rate for how good you would recommend SIGSEV to your friends and colleagues between 1 and 5.

Thanks for your patience,
SIGSEV

**Comment by dope** [comment]
I hope to god nobody is getting fired for this.
