### ISSUE TITLE
FAQ for lazy people

### ISSUE THREAD

**Issue by balthazar** [SIGSEV/Bridge#32]
Because apparently it's too complicated to read the first sentence instructing you should type <kbd>E</kbd> to go in edit mode, we should have a question mark at the bottom left with this info as a hint. And then disable it as soon as they used <kbd>E</kbd> enough (let's say 10 togglings at least), in order to get a real clean UI.

**Comment by meriadec** [comment]
too complicated to implement sorry

**Comment by balthazar** [comment]
Agréé
