### ISSUE TITLE
Autopublish

### ISSUE THREAD

**Issue by balthazar** [SIGSEV/Bridge#33]

**Comment by meriadec** [comment]
nice

**Comment by balthazar** [comment]
Still working on this piece of shit build

**Comment by balthazar** [comment]
It works even faster with the autopublish than manually, awesome.

**Comment by meriadec** [comment]
![june-club-news-3](https://user-images.githubusercontent.com/315259/33543996-6625e962-d8d9-11e7-8413-af7aa12748a8.jpg)
