### ISSUE TITLE
Widget is broken

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/Bridge#36]
# hello my wi
dget is broken. can you pleas fix this behaviour

![2018-12-28_14-55-08_355x246](https://user-images.githubusercontent.com/315259/50517437-ac22e280-0ab0-11e9-857c-9481cfd0fb94.png)

if not i will look on other extension for my new tab

**Comment by balthazar** [comment]
Isn't that the expected behavior? It appears this is the LoadingIssue wi jet so your screenshot actually doesn't seem wrong at first sight.
Also we dropped support for Windows 98 in a recent release, just so you know

**Comment by meriadec** [comment]
i'm on vista so it sould be fine n
o?

can you debug asap

**Comment by balthazar** [comment]
For sure, once my payment is confirmed on `1Apercu6P9Vsip89EuAVq6kWc5t5KvnTYp` I'll gladly help!

**Comment by meriadec** [comment]
no prob can you send a link to an explorer for this address please?

**Comment by balthazar** [comment]
Of course! [Here it is](https://viewblock.io/bitcoin/address/1Apercu6P9Vsip89EuAVq6kWc5t5KvnTYp)

**Comment by meriadec** [comment]
![2018-12-29_15-19-45_259x129](https://user-images.githubusercontent.com/315259/50539239-3173c900-0b7d-11e9-9f26-5475013bc8da.png)

my pleasure

**Comment by meriadec** [comment]
to prove it's yours, can you send 0.001 BTC to yourself and paste the tx hash here?

**Comment by balthazar** [comment]
```
pas de sushi!
HPVFv1gvM8AdeCZgrKkSaCPj4UOwUNZm2p5z9HJUf2mbGYQjgyN8NMJHfHPAorBcdFLUUMxF/gvYan5CFurONlQ=
```

**Comment by meriadec** [comment]
https://support.freewallet.org/support/solutions/articles/9000097169-what-is-transaction-hash-and-how-to-find-it-

don't thanks me it's ok :wink: :thumbs_up:

**Comment by meriadec** [comment]
[still no 0.001 BTC tx](https://www.blockchain.com/btc/address/1Apercu6P9Vsip89EuAVq6kWc5t5KvnTYp) as expected. closing this
