### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by balthazar** [SIGSEV/Bridge#38]
Long awaited by our millions users, it will come eventually.

**Comment by meriadec** [comment]
is there a bug in dark theme? i don't have it

**Comment by balthazar** [comment]
The webstore is cucked and requires a manual review that can take 2 weeks for every deploy, so if you want it now I would recommend building it and loading the unpacked extension

**Comment by meriadec** [comment]
K WILLt ry to figure out how to do that aha
